## Sampling rate
DAC_VRVQ_FeatureDenoise.sample_rate: 16000
Discriminator.sample_rate: 16000

# Data
batch_size: 16
# train/AudioDataset_EARS_Paired.duration: 0.38
train/AudioDataset_EARS_Paired.duration: 1.14
train/AudioDataset_EARS_Paired.n_examples: 10000000


val_batch_size: 4
val/AudioDataset_EARS_Paired.duration: 3.0
val/AudioDataset_EARS_Paired.n_examples: 32

# batch_size_test: 1
# test/AudioDataset.duration: 10.0
# test/build_transform.augment_prob: 0.0
# test/AudioDataset.n_examples: 100  ## this setting
# test/AudioDataset.n_examples: 40  ## just for temp
# test/AudioDatasetNoisyClean.duration: 3.0
# test/AudioDatasetNoisyClean.duration: 1.5
# test/AudioDatasetNoisyClean.n_examples: 150

# AudioLoader.shuffle: true
# AudioDataset.without_replacement: true

AudioLoader_EARS_Paired.shuffle: true
AudioDataset_EARS_Paired.without_replacement: true

train/build_dataset.folders:
        clean:
                - /home/shaokai/seCodec251209/train_clean.lst

        noisy:
                - /home/datasets/data_shaokai/train_noisy_libritts.lst


val/build_dataset.folders:
        clean:
                - /home/shaokai/seCodec251209/dev_clean.lst
        noisy:
                - /home/datasets/data_shaokai/val_noisy_libritts.lst

test/build_loader.folders:
        clean:
                - /home/shaokai/seCodec251209/test-clean_16khz.lst

        noisy:
                - /home/shaokai/seCodec251209/test_noisy_snr/16khz/snr_-10

test_mamba/build_loader.folders:
        clean:
                - /home/shaokai/seCodec251209/test-clean_16khz.lst

        est_mamba:
                - /home/shaokai/seCodec251209/test_noisy_snr/16khz/snr_-10

# test/build_dataset.folders:
#         speech_clean:
#                 # - /data/yoongidata/data/voicebank-demand-48k-encodec-3sec-24kbps/clean_testset_wav
#                 - /data/yoongidata/data/voicebank_demand/clean_testset_wav

#         speech_noisy:
#                 # - /data/yoongidata/data/voicebank-demand-48k-encodec-3sec-24kbps/noisy_testset_wav
#                 - /data/yoongidata/data/voicebank_demand/noisy_testset_wav

